# Generated by Django 3.1.6 on 2021-02-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandwich',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='sand_ing',
            name='sandwich',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='sandwiches.sandwich'),
        ),
    ]
