# Generated by Django 3.1.6 on 2021-02-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0002_auto_20210202_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sand_ing',
            name='ingredient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='sandwiches.ingredient'),
        ),
    ]
