# Generated by Django 3.1.6 on 2021-02-02 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0004_auto_20210202_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
